const movesWithDashes = [
    "All-Out Pummeling",
    "Baby-Doll Eyes",
    "Double-Edge",
    "Freeze-Dry",
    "G-Max Befuddle",
    "G-Max Cannonade",
    "G-Max Centiferno",
    "G-Max Chi Strike",
    "G-Max Cuddle",
    "G-Max Depletion",
    "G-Max Drum Solo",
    "G-Max Finale",
    "G-Max Fireball",
    "G-Max Foam Burst",
    "G-Max Gold Rush",
    "G-Max Gravitas",
    "G-Max Hydrosnipe",
    "G-Max Malodor",
    "G-Max Meltdown",
    "G-Max One Blow",
    "G-Max Rapid Flow",
    "G-Max Replenish",
    "G-Max Resonance",
    "G-Max Sandblast",
    "G-Max Smite",
    "G-Max Snooze",
    "G-Max Steelsurge",
    "G-Max Stonesurge",
    "G-Max Stun Shock",
    "G-Max Sweetness",
    "G-Max Tartness",
    "G-Max Terror",
    "G-Max Vine Lash",
    "G-Max Volcalith",
    "G-Max Volt Crash",
    "G-Max Wildfire",
    "G-Max Wind Rage",
    "Lock-On",
    "Mud-Slap",
    "Multi-Attack",
    "Never-Ending Nightmare",
    "Power-Up Punch",
    "Savage Spin-Out",
    "Self-Destruct",
    "Soft-Boiled",
    "Soul-Stealing 7-Star Strike",
    "Topsy-Turvy",
    "Trick-or-Treat",
    "U-turn",
    "V-create",
    "Wake-Up Slap",
    "Will-O-Wisp",
    "X-Scissor"
];

export default movesWithDashes;